/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/
#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"
//#include "scope.h"

// Widupdate groups
#define GROUP_DEFAULT 0

#define DOT_ON 2
#define DOT_OFF 3
#define TOP_UI_Y	30
#define BOTTOM_UI_Y	200 //240-40
#define DSO_CENTER_Y (BOTTOM_UI_Y+TOP_UI_Y)/2


#define DSO_DISP_W	320
#define DSO_DISP_H	170


#define T_Div_Button_ID 0
#define V_Div_Button_ID 1
#define Y_Trg_Button_ID 2
#define X_A_Button_ID 3
#define X_B_Button_ID 4
#define Y_A_Button_ID 5
#define Y_B_Button_ID 6


#define T_Div_List_ID 10
#define V_Div_List_ID 11
#define VERTI 0
#define HORIZ 1

// GListeners
extern GListener glistener;

// extern GHandles
extern GHandle ghContainerPage0;
extern GHandle Label_CH;

extern GHandle T_Div_Button;
extern GHandle T_Div_Label;
extern GHandle T_Div_List;


extern GHandle V_Div_Button;
extern GHandle V_Div_Label;
extern GHandle V_Div_List;

extern GHandle Label_X;
extern GHandle X_A_Label;
extern GHandle X_A_Button;
extern GHandle X_B_Label;
extern GHandle X_B_Button;
extern GHandle X_F_Label;
extern GHandle X_F_Label_Txt;
extern GHandle X_AB_Label;
extern GHandle X_AB_Label_Txt;

extern GHandle Label_Y;
extern GHandle Y_A_Label;
extern GHandle Y_A_Button;
extern GHandle Y_B_Label;
extern GHandle Y_B_Button;
extern GHandle Y_AB_Label;
extern GHandle Y_AB_Label_Txt;
extern GHandle Y_Trg_Label;
extern GHandle Y_Trg_Label_Txt;

extern GHandle Label_CH1;
extern GHandle CH1_RMS_Label;
extern GHandle CH1_RMS_Label_Txt;


extern GHandle CH1_SF_Label;
extern GHandle CH1_SF_Label_Txt;
extern GHandle CH1_Max_Label;
extern GHandle CH1_Max_Label_Txt;
extern GHandle CH1_PP_Label;
extern GHandle CH1_PP_Label_Txt;
extern GHandle CH1_AVG_Label;
extern GHandle CH1_AVG_Label_Txt;
extern GHandle CH1_Min_Label;
extern GHandle CH1_Min_Label_Txt;
extern GHandle CH1_Pk_Label;
extern GHandle CH1_Pk_Label_Txt;
extern GHandle CH1_P_Label;
extern GHandle CH1_P_Label_Txt;

extern GHandle Label_CH2;
extern GHandle CH2_Label;
extern uint16_t ADC_buffer[][320];
extern float ADC_Vmax;
extern int TIME_STEP;
// Function Prototypes



void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);
void updateMeasData(void);

static inline float screenY_to_V(int Y)
{
	//200-->0 ,30->3
	return (DSO_DISP_H-(Y-TOP_UI_Y))*ADC_Vmax/DSO_DISP_H;
}
static inline int screenX_to_T(int X)
{
	//200-->0 ,30->3
	return X*TIME_STEP;
}
static bool UI_data_ready;

#endif /* _GUI_H_ */

